name: Publish

on:
  push:
    branches:
      - master
      # for testing the GH Action without merging to master,
      # in some cases
      - test-publish-snapshots
    tags: ["*"]

jobs:
  sbt:
    name: sbt publish
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0
      - name: Set up JDK 11
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0-9
      - name: Publish
        run: |-
          sudo apt-get install graphviz
          sbt +mimaReportBinaryIssues
          sbt whitesourceCheckPolicies
          sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          WHITESOURCE_PASSWORD: ${{ secrets.WHITESOURCE_PASSWORD }}

  # TODO publish gradle from here as well

  documentation:
    name: Documentation
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0
      - name: Set up JDK 16
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.16.0-1
      - name: Publish
        run: |-
          eval "$(ssh-agent -s)"
          echo $SCP_SECRET | base64 -d > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
          ssh-add /tmp/id_rsa
          # using Scala 2.13 here to avoid the infamous problem with missing AskSupport in classpath
          sbt -Dakka.build.scalaVersion=2.13.0 -Dakka.genjavadoc.enabled=true publishRsync
        env:
          SCP_SECRET: ${{ secrets.SCP_SECRET }}
