name: Build Akka with Scala 3

on:
  push:
  # pull_request:
  # push:
  #   branches:
  #     - master
  #   tags-ignore: [ v.* ]

jobs:
  setup-runner:
    name: Setup runner
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0-9

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.2

  test:
    name: Compile and run tests on Scala 3
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        command:
          - akka-actor-tests/test
          - akka-actor-testkit-typed/test
          - akka-actor-tests/test
          - akka-actor-testkit-typed/test
          - akka-actor-typed/compile
          - akka-actor-typed-tests/test
          - akka-cluster/test/compile
          - akka-coordination/test
          - akka-discovery/test
          - akka-pki/test
          - akka-protobuf/test
          - akka-protobuf-v3/test
          - akka-serialization-jackson/test:compile
          - akka-slf4j/test
          - akka-stream/test
          - akka-stream-testkit/test
          - akka-stream-tests-tck/test
          - akka-remote/test
          - akka-remote-tests/test
          - akka-testkit/test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0-9

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.2
      - name: Compile and test selected modules on Scala 3
        run: |
          sbt -jvm-opts .jvmopts-ci \
            -Dakka.build.scalaVersion=3.0 \
            -Dakka.test.multi-in-test=false \
            -Dakka.test.tags.exclude=performance,timing,long-running \
            ${{ matrix.command }}
